feat: added color to theme
PhelipeLB/Crud-beer pull request #23
Opened 2023-02-01 22:36 UTC by PhelipeLB

2023-02-02 12:01 UTC, NandoGoulartt requested changes
Use theme.ts from crud-beer/pakage/ui/src/theme.ts

2023-02-03 13:12 UTC, daniloab approved these changes
same said for @NandoGoulartt 

when using colors avoid to place them directly `#00000`. Prefer to consume from https://chakra-ui.com/docs/hooks/use-theme

let to do this in another pull request. 

Lets move forward!

2023-02-03 13:12 UTC, daniloab commented
also @NandoGoulartt help @PhelipeLB to fix the conflict

2023-02-03 13:28 UTC, NandoGoulartt approved these changes

2023-02-03 13:53 UTC, merged